Test dtd2cduce. The enable_if option for cram tests seems to be broken
with dune < 3.0, so we hack around the absence of dtd2cduce.
  $ (test -f ../../../../../install/default/bin/dtd2cduce && ../../../../../install/default/bin/dtd2cduce '' test.dtd)|| cat test.cd
  (* This file has been automatically generated by dtd2cduce *)
  type DESCRIPTION = <DESCRIPTION>[ ( Char )* ];;
  type TITLE = <TITLE LANGUAGE=?String RATING=?String>[ ( Char )* ];;
  type TIME = <TIME>[ ( Char )* ];;
  type PROGRAMSLOT = <PROGRAMSLOT VTR=?String>[ (TIME TITLE DESCRIPTION?) ];;
  type DATE = <DATE>[ ( Char )* ];;
  type HOLIDAY = <HOLIDAY>[ ( Char )* ];;
  type DAY = <DAY>[ (DATE (HOLIDAY | PROGRAMSLOT+)+) ];;
  type BANNER = <BANNER>[ ( Char )* ];;
  type CHANNEL = <CHANNEL CHAN=String>[ (BANNER DAY+) ];;
  type TVSCHEDULE = <TVSCHEDULE NAME=String>[ CHANNEL+ ];;
